name: filament_manager
description: "3D Farm Manager"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.1.0-alpha+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.8

  sqflite: ^2.3.3
  path: ^1.9.0
  uuid: ^4.4.0

  image_picker: ^1.0.7
  google_mlkit_text_recognition: ^0.11.0

  camera: ^0.10.5+9
  cross_file: ^0.3.4+2
  
  flutter_colorpicker: ^1.0.3



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  flutter_native_splash: ^2.4.0

  flutter_launcher_icons: ^0.13.1

flutter:

  uses-material-design: true

  generate: true

  assets:
    - assets/splash.png

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash.png
  android: true
  ios: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/app_icon.png

