name: filament_manager
description: "Filament Manager"
publish_to: 'none'
version: 0.5.0-beta+8

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.8

  sqflite: ^2.3.3
  path: ^1.9.0
  uuid: ^4.4.0

  image_picker: ^1.0.7
  google_mlkit_text_recognition: ^0.15.0

  camera: ^0.10.5+9
  cross_file: ^0.3.4+2
  
  flutter_colorpicker: ^1.0.3

  # Export/Import packages
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  shared_preferences: ^2.5.4
  url_launcher: ^6.2.6
  file_picker: ^10.3.8
  package_info_plus: ^9.0.0
  flutter_markdown: ^0.7.7+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  flutter_native_splash: ^2.4.0

  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/splash.png
    - HELP.md

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash.png
  android: true
  ios: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/app_icon.png
